backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: "index"
    label: "Index"
    files:
      - file: "src/pages/index/index.md"
        label: "Index"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: Hero, name: hero, widget: object, fields:
              [
                {label: "Hero Title", name: "title", widget: "string"},
                {label: "Hero Description", name: "description", widget: "markdown"}
              ]
            }
          - {label: About, name: about, widget: object, fields:
              [
                {label: "About Title", name: "title", widget: "string"},
                {label: "About Description Col 1", name: "col_1", widget: object, fields:
                  [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Description", name: "description", widget: "markdown"}
                  ]
                },
                {label: "About Description Col 2", name: "col_2", widget: object, fields:
                  [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Description", name: "description", widget: "markdown"}
                  ]
                }
              ]
            }
          - {label: Location, name: loc, widget: object, fields:
              [
                {label: "Location Title", name: "title", widget: "string"},
                {label: "Location Description", name: "description", widget: "markdown"},
                {label: "Location Marker", name: "marker", widget: "markdown"},
                {label: "Location Coords", name: "coords", widget: object, fields:
                  [
                    {label: "Latitude", name: "lat", widget: "number"},
                    {label: "Longitude", name: "lng", widget: "number"}
                  ]
                }
              ]
          }
          - {label: Featured Images, name: featured_images, widget: object, fields:
            [
              {
                label: "Gallery",
                name: "image_list",
                widget: "list",
                field: {label: Image, name: image, widget: image}
              }
            ]
          }
          - {label: Sponsors, name: sponsors, widget: object, fields:
            [
              {label: "Sponsors Title", name: "title", widget: "string"},
              {label: "Sponsors Description", name: "description", widget: "markdown"},
              {
                label: "Sponsors List",
                name: "sponsor_list",
                widget: "list",
                fields: [
                  {label: Image, name: image, widget: image},
                  {label: Link, name: link, widget: "text"},
                  {label: Tier, name: tier, widget: "select", options: ["bronze", "silver", "gold"]},
                  {label: "Alt Text", name: alt, widget: "text"}
                ]
              }
            ]
          }
          - {label: Featured Event, name: featured_event, widget: object, fields:
            [
              {label: "Event Title", name: "title", widget: "string"},
              {label: "Event Subtitle", name: "subtitle", widget: "string"},
              {label: "Event Description", name: "desc", widget: "markdown"},
              {label: "Event Image", name: "image", widget: "image"},
              {label: "Event Link", name: "link", widget: "text"}
            ]
          }
          - {label: Events, name: events, widget: list, fields: [
              {label: "Event Title", name: title, widget: "string"},
              {label: "Event Subtitle", name: subtitle, widget: "string"},
              {label: "Event Description", name: desc, widget: "markdown"},
              {label: "Event Image", name: image, widget: "image"},
              {label: "Event Link", name: link, widget: "text"}
            ]
          }
          